language: python
sudo: required
dist: trusty
cache:
  directories:
    - .sources
matrix:
  include:
    - python: 2.7
      env:
        - TENSORFLOW="0.12.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
    - python: 3.4
      env:
        - TENSORFLOW="0.12.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
    - python: 3.5
      env:
        - TENSORFLOW="0.12.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
install:
  - source bin/conda.sh
  - source bin/install.sh --python "$TRAVIS_PYTHON_VERSION" --tensorflow "$TENSORFLOW" --nauty "$NAUTY" --pynauty "$PYNAUTY" test
script:
  - bash bin/test.sh
after_success:
  - codecov
notifications:
  email: false
