language: python
sudo: required
dist: trusty
cache:
  directories:
    - .sources
    - datasets
matrix:
  include:
    - python: 2.7
      env:
        - TENSORFLOW="0.11.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
    - python: 3.4
      env:
        - TENSORFLOW="0.11.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
    - python: 3.5
      env:
        - TENSORFLOW="0.12.0"
        - NAUTY="26r7"
        - PYNAUTY="0.6.0"
install:
  - source ci/install.sh
script:
  - bash bin/test.sh
after_success:
  - codecov
notifications:
  email: false
